services:
  mongo:
    image: mongo:7
    container_name: vanderlande-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"  # Deze regel zorgt ervoor dat je Python script verbinding kan maken
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - ./data/mongo:/data/db